version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: bookstore_backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/bookstore
      - JWT_SECRET=bestsecretkey256018
    depends_on:
      - mongo

volumes:
  mongo_data: